language: go

# Only clone the most recent commit.
git:
  depth: 1

notifications:
  email: false

go:
- master #latest

before_install:
  - go get github.com/mattn/goveralls

script:
- $GOPATH/bin/goveralls -service=travis-ci